### ISSUE TITLE
Step-by-step Installation guide?

### ISSUE THREAD

**Issue by smille2** [ramses0/xscreensaver-pi-hdmi#2]
Hello,

this script looks like the thing I am looking for. My problem ist that I am a totally newbie to linux.

Is it possible that you provide a step-by-step installation guide?

Thank you
Stefan

**Comment by ramses0** [comment]
I can't give you direct tech support, but here's the gist of it and I'll give you a slightly modified instruction set which should be a little easier:
Download this file: https://raw.githubusercontent.com/ramses0/xscreensaver-pi-hdmi/master/bin/xscreensaver-pi-hdmi
Save it in your home directory as "xscreensaver-pi-hdmi" (you can even just copy/paste the text into a file).
  # (type this directly, it'll ask for your root/admin/user password)  # direct control of HDMI / framebuffer needs special permissions  sudo adduser $USER video
  # you need xscreensaver installed first too  sudo apt-get install xscreensaver
You want to put the following lines into a file called "~/.xsession".  Use the command "nano ~/.xsession" as a basic editor:
  # start xscreensaver  xscreensaver &
  # start xscreensaver status monitor  sh ~/xscreensaver-pi-hdmi &
...then do "Ctrl-X" to exit, and say "yes" to save changes, and press "enter" to save it to ~/.xsession
Hopefully it'll work, you might have to log or restart your pi to try it out.
--Robert

**Comment by smille2** [comment]
Thank you very much.

Power off works fine. For power on I had to change the script:
(line 55)
   xrefresh -d :0.0
